version: "3"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    privileged: true
    command: /sbin/init
    ports:
      - "2222:22"